### ISSUE TITLE
java.lang.LinkageError: Method java.lang.String 

### ISSUE THREAD

**Issue by midhilajm** [charbgr/litho-picasso#2]
My code

      ```
  final ComponentContext context = new ComponentContext(this);

       Component component=   PicassoImage.create(context)
                .imageUrl(
                              "https://d2b41ce3jhhjt0.cloudfront.net/uploads/social/posts/medium/c57365ec934af9814503ae2de8d252e9.jpg"

                )
                .fit(true)
                .centerCrop(true)
                .build();

        //        "https://d2b41ce3jhhjt0.cloudfront.net/uploads/social/posts/medium/c57365ec934af9814503ae2de8d252e9.jpg"



        setContentView(LithoView.create(context, component));
```

>   java.lang.LinkageError: Method java.lang.String com.github.charbgr.litho.picasso.PicassoImage$PicassoImageImpl.getSimpleName() overrides final method in class Lcom/facebook/litho/Component; (declaration of 'com.github.charbgr.litho.picasso.PicassoImage$PicassoImageImpl' appears in /data/app/com.midhilaj.myapplication-1/split_lib_dependencies_apk.apk)
>         at com.github.charbgr.litho.picasso.PicassoImage.create(PicassoImage.java:170)
>         at com.midhilaj.myapplication.MainActivity.onCreate(MainActivity.java:45)
>         at android.app.Activity.performCreate(Activity.java:6667)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
>         at android.app.ActivityThread.-wrap12(ActivityThread.java)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
>         at android.os.Handler.dispatchMessage(Handler.java:110)
>         at android.os.Looper.loop(Looper.java:203)
>         at android.app.ActivityThread.main(ActivityThread.java:6253)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
>

**Comment by charbgr** [comment]
Which version of Picasso? Litho?

Can you please provide a sample project?

**Comment by charbgr** [comment]
Close due to inactivity.
